<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>TLOverlay.Core</RootNamespace>
    <AssemblyName>TLOverlay.Core</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" Version="8.0.*" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.*" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="TLOverlay.Core.Tests" />
  </ItemGroup>

</Project>
