<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <UseWPF>true</UseWPF>
    <RootNamespace>TLOverlay.App</RootNamespace>
    <AssemblyName>TLOverlay</AssemblyName>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon />
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Serilog" Version="4.*" />
    <PackageReference Include="Serilog.Extensions.Logging" Version="8.*" />
    <PackageReference Include="Serilog.Sinks.File" Version="6.*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TLOverlay.Core\TLOverlay.Core.csproj" />
  </ItemGroup>

</Project>
